---
title: "Data Visualization Project Proposal"
author: "Malachy McAvoy"
date: "2022-04-12"
output:
  html_document:
    theme: darkly
    highlight: textmate
---

# DANL-310 Project Proposal   

  For my project proposal, I’ve decided to merge two of my greatest passions—coding and sports—into a fun and insightful analysis. My project will explore the relationships between NFL combine performance, college statistics, and subsequent NFL success. Using data from the NFL combine and players’ college achievements, I aim to determine if there are any significant correlations that can predict a player's professional success in the NFL.

  While this analysis may seem trivial to some, it holds substantial value for those deeply invested in the sport—ranging from fans to team executives. For NFL front offices, drafting the right player is a high-stakes decision that involves significant time and financial investments. A poor selection can result in millions of dollars wasted on a bad contract, and consecutive missteps in drafting can derail a franchise's long-term goals, including their chances at a Super Bowl. Therefore, maximizing draft success is critical, and analytics can provide a competitive edge. It's becoming clear that modern sports are embracing the power of analytics, and the NFL should fully integrate this strategy to evaluate player potential more effectively.

  My hypothesis is that a player’s performance in both the combine and college significantly impacts their NFL career success. The null hypothesis for this study is that there is no relationship between a player’s combine performance, college statistics, and their success in the NFL. To test this, I have already gathered data from Sports Reference on all players drafted from 2001 to 2021, including their combine measurements. Although I faced challenges in collecting the college data for drafted players, I reached out to Professor Kirk Anne for help with scraping the necessary information. To analyze the data, I plan to create dummy variables for each combine category and college statistic, establishing benchmarks for each position to assess their predictive power.

